# POST http://localhost:3000/api/sign-in 
# Content-Type: application/json

# {  
#     "fullname" : "nikhil", 
#     "email": "nikhilsharma270027@gmail.com",  
#     "password": "123456"  
# }


GET  http://localhost:3000/api/check-username-unique?username=one
Content-Type: application/json

# {  
#     "fullname" : "nikhil", 
#     "email": "nikhilsharma270027@gmail.com",  
#     "password": "123456"  
# }